// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehouqzdyjgdnnmxcgidb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVob3VxemR5amdkbm5teGNnaWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyOTIyMTgsImV4cCI6MjA3MDg2ODIxOH0.ML0QXeWo-a-G0vaXJ3XUzolWE0gfX1plOz8L-g6Ea88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});